# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'stuhub' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for stuhub

  pod 'react-native-sensitive-info', :path => '../node_modules/react-native-sensitive-info'

  pod 'RNCViewpager', :path => '../node_modules/@react-native-community/viewpager'

  target 'stuhubTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

pod 'DCTAuth', :git => 'https://github.com/danielctull/DCTAuth.git'
